### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by nelduarte** [MassOS-Linux/massos-linux.github.io#1]
Hi, what is your package manager so that I can install applications from the terminal?
Thank you.

**Comment by DanielMYT** [comment]
The recommended way to install apps is through Flatpak or AppImages. AppImages can be downloaded, marked as executable and run directly. The `flatpak` command can be used from the terminal to install Flatpak apps.

You may be able to compile additional programs you need from source. MassOS includes development tools and headers to allow you to do that. Documentation regarding compiling from source is also upcoming on the MassOS wiki.

If you think the utility you want should be included in MassOS and you think most people would want it, you can open a feature request at https://github.com/MassOS-Linux/MassOS/issues. Huge programs are unlikely to be accepted, however we may accept small programs like useful command-line utilities. Also, any suggested software must be either in the public domain, or covered by a [GPL-compatible license](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

There isn't currently a traditional "system" package manager, however [one is in development](https://github.com/MassOS-Linux/masspkg). At the time of writing this comment, it is mostly finished and working, but has some rough edges. Contributions to it are welcome and highly encouraged. For it to work, we will also need a team of maintainers and some form of hosting. See [this](https://github.com/MassOS-Linux/masspkg/blob/main/README.md#current-status) for more information.

Please also open issues on the [main MassOS repository](https://github.com/MassOS-Linux/MassOS) in future, since this repository is specifically for the MassOS website.
